Resources:
  TwitterUserTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete # switch to Retain when done 
    Properties:
      TableName: ${self:custom.userTableName}
      AttributeDefinitions:
        - AttributeName: twitter_username
          AttributeType: S
      KeySchema:
        - AttributeName: twitter_username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: ${self:custom.resourceTagKey}
          Value: ${self:custom.resourceTagValue}