Resources:
  TwitterTweetsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete # switch to Retain when done
    Properties:
      TableName: ${self:custom.tweetsTableName}
      AttributeDefinitions:
        - AttributeName: airport_city
          AttributeType: S
        - AttributeName: tweet_id
          AttributeType: N
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: airport_city
          KeyType: HASH
        - AttributeName: tweet_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: ${self:custom.tweetsTableName-CreatedDate-Index}
          KeySchema:
            - AttributeName: airport_city
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
      Tags:
        - Key: ${self:custom.resourceTagKey}
          Value: ${self:custom.resourceTagValue}