Resources:
  NewDealTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "New Flight Deals Available"
      TopicName: new-flight-deals-on-twitter
      Subscription:
        -
          Protocol: sms
          Endpoint: ${opt:sms-phone-number}

Outputs:
  SNSTopicId:
    Value:
      Ref: NewDealTopic
